name: Build

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build
        run: dotnet build --configuration Release
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
