name: Build

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 6.0.x
      #     include-prerelease: true

      # - name: Build
      #   run: dotnet build --configuration Release
      #   env:
      #     DOTNET_CLI_TELEMETRY_OPTOUT: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '[17.0,18.0)'
          msbuild-architecture: x64

      - name: Build
        run: msbuild /p:Configuration=Release /restore -m

      - name: Pack
        run: msbuild /p:Configuration=Release /t:Pack
